"""
Validation script for post-net-zero gas concentrations.

This script validates that constituent gases maintain constant (flat-line) values
after the net-zero year in the extended scenario files generated by notebook 101.

Usage:
    python 103_validation.py

Outputs:
    - Console summary of pass/fail results
    - Plots saved to output/validation_plots/
"""

import os
from pathlib import Path

import dotenv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yaml

# Load environment variables
dotenv.load_dotenv()

# Set up output folder
OUTPUT_FOLDER = Path(os.environ["OUTPUT_FOLDER"])
OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)

# Configuration
GHG_MAPPING_FILE = Path("ghg_mapping.yml")
NETZERO_TIMINGS_FILE = OUTPUT_FOLDER / "101_netzero_timings.csv"
CO2_EXTENDED_FILE = OUTPUT_FOLDER / "101_netzero_co2_extended.csv"
KYOTO_EXTENDED_FILE = OUTPUT_FOLDER / "101_netzero_kyoto_extended.csv"
PLOT_OUTPUT_DIR = OUTPUT_FOLDER / "validation_plots"

# Number of sample scenarios to plot for each aggregate
N_SAMPLE_PLOTS = 3


def load_data():
    """Load all required data files."""
    with open(GHG_MAPPING_FILE) as f:
        ghg_mapping = yaml.safe_load(f)

    nz_timings = pd.read_csv(NETZERO_TIMINGS_FILE, index_col=[0, 1])
    co2_extended = pd.read_csv(CO2_EXTENDED_FILE)
    kyoto_extended = pd.read_csv(KYOTO_EXTENDED_FILE)

    return ghg_mapping, nz_timings, co2_extended, kyoto_extended


def validate_flatline(df, nz_timings, nz_column, scenario_suffix, constituent_vars, aggregate_name):
    """
    Validate that constituent gases stay flat after net-zero year.

    Args:
        df: DataFrame with extended scenario data
        nz_timings: DataFrame with net-zero timing metadata
        nz_column: Column name for net-zero year in nz_timings
        scenario_suffix: Suffix added to scenario names (e.g., "_NZCO2")
        constituent_vars: List of constituent variable names to check
        aggregate_name: Name of the aggregate variable for reporting

    Returns:
        Dict with 'pass' and 'fail' lists containing validation results
    """
    results = {"pass": [], "fail": []}

    # Get year columns (numeric columns)
    year_cols = [c for c in df.columns if c.isdigit()]

    # Get net-zero years for scenarios
    nz_years = nz_timings[nz_column].dropna()

    for (model, scenario), nz_year in nz_years.items():
        nz_year = int(nz_year)
        extended_scenario = f"{scenario}{scenario_suffix}"

        for var in constituent_vars:
            # Find matching row
            mask = (df['model'] == model) & (df['scenario'] == extended_scenario) & (df['variable'] == var)
            matching_rows = df[mask]

            if matching_rows.empty:
                continue

            row = matching_rows.iloc[0]

            # Get value at net-zero year
            nz_year_str = str(nz_year)
            if nz_year_str not in year_cols:
                continue

            nz_value = row[nz_year_str]

            # Get years after net-zero
            post_nz_years = [y for y in year_cols if int(y) > nz_year]

            # Check each year after net-zero
            deviation_found = False
            for year in post_nz_years:
                year_value = row[year]
                # Use small tolerance for floating point comparison
                if abs(year_value - nz_value) > 1e-10:
                    results["fail"].append({
                        "aggregate": aggregate_name,
                        "variable": var,
                        "model": model,
                        "scenario": extended_scenario,
                        "nz_year": nz_year,
                        "expected_value": nz_value,
                        "deviation_year": int(year),
                        "deviation_value": year_value
                    })
                    deviation_found = True
                    break

            if not deviation_found:
                results["pass"].append({
                    "aggregate": aggregate_name,
                    "variable": var,
                    "model": model,
                    "scenario": extended_scenario,
                    "nz_year": nz_year,
                    "nz_value": nz_value
                })

    return results


def create_validation_plots(df, nz_timings, nz_column, scenario_suffix, constituent_vars,
                            aggregate_name, output_dir, n_samples=3):
    """
    Create illustrative plots showing flat-line behavior after net-zero.

    Args:
        df: DataFrame with extended scenario data
        nz_timings: DataFrame with net-zero timing metadata
        nz_column: Column name for net-zero year
        scenario_suffix: Suffix added to scenario names
        constituent_vars: List of constituent variable names
        aggregate_name: Name of the aggregate variable
        output_dir: Directory to save plots
        n_samples: Number of sample scenarios to plot
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Get year columns
    year_cols = sorted([c for c in df.columns if c.isdigit()], key=int)
    years = [int(y) for y in year_cols]

    # Get net-zero years and sample scenarios
    nz_years = nz_timings[nz_column].dropna()

    # Sample scenarios with varying net-zero years for diversity
    nz_years_sorted = nz_years.sort_values()
    n_total = len(nz_years_sorted)

    if n_total == 0:
        print(f"  No scenarios found for {aggregate_name}")
        return

    # Select scenarios at different points (early, middle, late net-zero)
    indices = np.linspace(0, n_total - 1, min(n_samples, n_total), dtype=int)
    sample_scenarios = [nz_years_sorted.index[i] for i in indices]

    for model, scenario in sample_scenarios:
        nz_year = int(nz_years[(model, scenario)])
        extended_scenario = f"{scenario}{scenario_suffix}"

        # Create figure with subplots for each constituent
        n_vars = len(constituent_vars)
        # Adjust height per subplot based on number of variables
        height_per_var = 2.5 if n_vars > 5 else 3
        fig, axes = plt.subplots(n_vars, 1, figsize=(12, height_per_var * n_vars), sharex=True)
        if n_vars == 1:
            axes = [axes]

        fig.suptitle(f"{model} | {extended_scenario}\nNet-zero year: {nz_year}",
                     fontsize=12, fontweight='bold')

        for ax, var in zip(axes, constituent_vars):
            # Find matching row
            mask = (df['model'] == model) & (df['scenario'] == extended_scenario) & (df['variable'] == var)
            matching_rows = df[mask]

            if matching_rows.empty:
                ax.text(0.5, 0.5, f"No data for {var}", ha='center', va='center', transform=ax.transAxes)
                ax.set_ylabel(var.split('|')[-1])
                continue

            row = matching_rows.iloc[0]
            unit = row['unit']
            values = [row[y] for y in year_cols]

            # Plot the timeseries
            ax.plot(years, values, 'b-', linewidth=1.5, label='Emissions')

            # Mark the net-zero year
            ax.axvline(x=nz_year, color='red', linestyle='--', linewidth=2, label=f'Net-zero year ({nz_year})')

            # Highlight the flat-line region
            post_nz_mask = np.array(years) >= nz_year
            if any(post_nz_mask):
                nz_value = row[str(nz_year)]
                ax.axhline(y=nz_value, color='green', linestyle=':', linewidth=1.5,
                          alpha=0.7, label=f'Flat-line value ({nz_value:.2f})')

                # Shade the post-net-zero region
                ax.axvspan(nz_year, max(years), alpha=0.1, color='green')

            ax.set_ylabel(f"{var.split('|')[-1]}\n({unit})", fontsize=9)
            ax.grid(True, alpha=0.3)
            ax.legend(loc='upper right', fontsize=8)

        axes[-1].set_xlabel('Year')

        plt.tight_layout()

        # Save plot
        safe_model = model.replace('/', '_').replace(' ', '_')
        safe_scenario = extended_scenario.replace('/', '_').replace(' ', '_')
        filename = f"{aggregate_name.replace('|', '_')}_{safe_model}_{safe_scenario}.png"
        plt.savefig(output_dir / filename, dpi=150, bbox_inches='tight')
        plt.close()

        print(f"  Saved: {filename}")


def print_summary(results, aggregate_name):
    """Print validation summary for an aggregate."""
    n_pass = len(results['pass'])
    n_fail = len(results['fail'])
    total = n_pass + n_fail

    print(f"\n{aggregate_name}:")
    print(f"  Total checks: {total}")
    print(f"  PASS: {n_pass}")
    print(f"  FAIL: {n_fail}")

    if results['fail']:
        print("\n  Failures:")
        for fail in results['fail'][:10]:
            print(f"    - {fail['variable']} in {fail['model']}/{fail['scenario']}")
            print(f"      Net-zero year: {fail['nz_year']}, Expected: {fail['expected_value']:.6f}")
            print(f"      Deviation at year {fail['deviation_year']}: {fail['deviation_value']:.6f}")

        if len(results['fail']) > 10:
            print(f"    ... and {len(results['fail']) - 10} more failures")


def main():
    print("=" * 80)
    print("POST-NET-ZERO VALIDATION")
    print("=" * 80)

    # Load data
    print("\nLoading data...")
    ghg_mapping, nz_timings, co2_extended, kyoto_extended = load_data()

    all_results = {"pass": [], "fail": []}

    # Validate CO2 extended scenarios
    print("\nValidating CO2 extended scenarios...")
    co2_results = validate_flatline(
        co2_extended,
        nz_timings,
        "year_netzero_co2",
        "_NZCO2",
        ghg_mapping["Emissions|CO2"],
        "Emissions|CO2"
    )
    all_results["pass"].extend(co2_results["pass"])
    all_results["fail"].extend(co2_results["fail"])
    print_summary(co2_results, "Emissions|CO2")

    # Validate Kyoto extended scenarios
    print("\nValidating Kyoto extended scenarios...")
    kyoto_results = validate_flatline(
        kyoto_extended,
        nz_timings,
        "year_netzero_kyoto_ar6gwp100",
        "_NZKyoto",
        ghg_mapping["Emissions|Kyoto Gases [AR6-GWP100]"],
        "Emissions|Kyoto Gases"
    )
    all_results["pass"].extend(kyoto_results["pass"])
    all_results["fail"].extend(kyoto_results["fail"])
    print_summary(kyoto_results, "Emissions|Kyoto Gases")

    # Overall summary
    print("\n" + "=" * 80)
    print("OVERALL SUMMARY")
    print("=" * 80)
    print(f"\nTotal checks: {len(all_results['pass']) + len(all_results['fail'])}")
    print(f"PASS: {len(all_results['pass'])}")
    print(f"FAIL: {len(all_results['fail'])}")

    if not all_results['fail']:
        print("\n✓ All constituent gases maintain constant values after net-zero year!")
    else:
        print("\n✗ Some validations failed. See details above.")

    # Create illustrative plots
    print("\n" + "=" * 80)
    print("CREATING VALIDATION PLOTS")
    print("=" * 80)

    print(f"\nSaving plots to {PLOT_OUTPUT_DIR}/")

    print("\nCO2 extended scenarios:")
    create_validation_plots(
        co2_extended,
        nz_timings,
        "year_netzero_co2",
        "_NZCO2",
        ghg_mapping["Emissions|CO2"],
        "Emissions_CO2",
        PLOT_OUTPUT_DIR,
        n_samples=N_SAMPLE_PLOTS
    )

    print("\nKyoto extended scenarios:")
    # Expand Emissions|CO2 to its constituents for plotting since the aggregate
    # doesn't exist in the extended file - only the individual gases were flat-lined
    kyoto_plot_vars = []
    for var in ghg_mapping["Emissions|Kyoto Gases [AR6-GWP100]"]:
        if var == "Emissions|CO2":
            # Replace with CO2 constituents
            kyoto_plot_vars.extend(ghg_mapping["Emissions|CO2"])
        else:
            kyoto_plot_vars.append(var)

    create_validation_plots(
        kyoto_extended,
        nz_timings,
        "year_netzero_kyoto_ar6gwp100",
        "_NZKyoto",
        kyoto_plot_vars,
        "Emissions_Kyoto",
        PLOT_OUTPUT_DIR,
        n_samples=N_SAMPLE_PLOTS
    )

    print("\nValidation complete!")

    return len(all_results['fail']) == 0


if __name__ == "__main__":
    import sys
    success = main()
    sys.exit(0 if success else 1)
